### ISSUE TITLE
Add parameter to gem

### ISSUE THREAD

**Issue by phlegx** [git-commit-notifier/git-commit-notifier#193]
Can you please add parameter mailinglist and repo path, so that I can use it as a hook please?

**Comment by rickbradshaw** [comment]
Has this ever been implemented? I would really like to be able to run with a "custom" list of people to be notified which the "-l" example above would be nice

**Comment by akzhan** [comment]
All logic incorporated into https://github.com/git-commit-notifier/git-commit-notifier/blob/master/lib/git_commit_notifier/executor.rb

You can add custom args passing logic there.
